name: Fix README Formatting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Markdown Linter and Formatter
        run: |
          pip install mdformat

      - name: Create Markdown Formatting Script
        run: |
          echo """import sys

          def format_whitelist(content: str) -> str:
              lines = content.split('\\n')
              formatted_lines = []
              inside_whitelist = False

              for line in lines:
                  stripped = line.strip()
                  
                  if stripped.lower() == "whitelist":
                      formatted_lines.append("## Whitelist\\n")
                      inside_whitelist = True
                      continue

                  if inside_whitelist:
                      if not stripped:
                          inside_whitelist = False
                      else:
                          formatted_lines.append(f"- {stripped}")
                  else:
                      formatted_lines.append(line)

              return '\\n'.join(formatted_lines)

          def ensure_header(content: str) -> str:
              if not content.startswith("Single File Programming Question"):
                  return "Single File Programming Question\\n\\n" + content
              return content

          for file in sys.argv[1:]:
              with open(file, 'r', encoding='utf-8') as f:
                  content = f.read()
              
              content = ensure_header(content)
              content = format_whitelist(content)

              with open(file, 'w', encoding='utf-8') as f:
                  f.write(content)
          """ > format_readme.py

      - name: Find and Fix README.md Files
        run: |
          find C/VIT/Sem-2/Assessments CPP/VIT/Sem-2/Assessments -type f -name "README.md" | while read file; do
            python format_readme.py "$file"
            mdformat "$file"
          done

      - name: Check for Changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Create PR for Whitelist Formatting Fix
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git checkout -b fix-readme-whitelist
          git add C/VIT/Sem-2/Assessments/**/README.md CPP/VIT/Sem-2/Assessments/**/README.md
          git commit -m "Format whitelist section in README files"

          git push origin fix-readme-whitelist

          gh pr create --title "Fix Whitelist Formatting in READMEs" --body "Formatted the whitelist section while preserving indentation and ensured each README starts with 'Single File Programming Question'."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
