name: Fix README Formatting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Markdown Linter and Formatter
        run: |
          pip install mdformat

      - name: Create Markdown Formatting Script
        run: |
          echo """import sys
          def convert_to_markdown(message: str) -> str:
              lines = message.split('\\n')
              markdown_lines = []
              
              for line in lines:
                  stripped = line.lstrip()
                  indent = len(line) - len(stripped)
                  
                  if stripped.startswith('Single File Programming Question'):
                      markdown_lines.append(f'{' ' * indent}# {stripped}')
                  elif stripped.startswith('Problem Statement'):
                      markdown_lines.append(f'{' ' * indent}## {stripped}')
                  elif stripped.startswith(('Input format', 'Output format', 'Code constraints', 'Sample test cases')):
                      markdown_lines.append(f'{' ' * indent}### {stripped}')
                  elif stripped.startswith(('Input ', 'Output ')):
                      markdown_lines.append(f'{' ' * indent}#### {stripped}')
                  else:
                      markdown_lines.append(line)
              
              return '\\n'.join(markdown_lines)

          for file in sys.argv[1:]:
              with open(file, 'r', encoding='utf-8') as f:
                  content = f.read()
              formatted_content = convert_to_markdown(content)
              with open(file, 'w', encoding='utf-8') as f:
                  f.write(formatted_content)
          """ > format_readme.py

      - name: Find and Fix README.md Files
        run: |
          find C/VIT/Sem-2/Assessments CPP/VIT/Sem-2/Assessments -type f -name "README.md" | while read file; do
            python format_readme.py "$file"
            mdformat "$file"
          done

      - name: Check for Changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Ensure the latest remote changes are pulled before pushing
          git pull --rebase origin main || git checkout main

          git add C/VIT/Sem-2/Assessments/**/README.md CPP/VIT/Sem-2/Assessments/**/README.md
          git commit -m "Fix README formatting issues and preserve indentation"
          git push origin main
