name: Fix README Formatting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Markdown Linter and Formatter
        run: |
          pip install mdformat

      - name: Create Markdown Formatting Script
        run: |
          echo """import sys
          def convert_to_markdown(message: str) -> str:
              lines = message.split('\n')
              markdown_lines = []
              
              for line in lines:
                  line = line.strip()
                  
                  if line.startswith('Single File Programming Question'):
                      markdown_lines.append(f'# {line}')
                  elif line.startswith('Problem Statement'):
                      markdown_lines.append(f'## {line}')
                  elif line.startswith('Input format') or line.startswith('Output format') or \
                       line.startswith('Code constraints') or line.startswith('Sample test cases'):
                      markdown_lines.append(f'### {line}')
                  elif line.startswith('Input ') or line.startswith('Output '):
                      markdown_lines.append(f'#### {line}')
                  else:
                      markdown_lines.append(line)
              
              return '\n'.join(markdown_lines)

          for file in sys.argv[1:]:
              with open(file, 'r', encoding='utf-8') as f:
                  content = f.read()
              formatted_content = convert_to_markdown(content)
              with open(file, 'w', encoding='utf-8') as f:
                  f.write(formatted_content)
          """ > format_readme.py

      - name: Find and Fix README.md Files
        run: |
          find C/VIT/Sem-2/Assessments -type f -name "README.md" | while read file; do
            python format_readme.py "$file"
            mdformat "$file"
          done

      - name: Check for Changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b fix-readme-formatting
          git add C/VIT/Sem-2/Assessments/**/README.md
          git commit -m "Fix README formatting issues"
          git push origin fix-readme-formatting

      - name: Create Pull Request
        if: env.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Fix README Formatting"
          body: "This PR fixes formatting issues in README files under C/VIT/Sem-2/Assessments and applies the standardized structure."
          branch: fix-readme-formatting
