name: Daily Tag Creator

on:
  schedule:
    - cron: "20 18 * * *" # Runs at 11:50 PM IST (18:20 UTC)
  workflow_dispatch:

jobs:
  create-daily-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Date Command
        run: sudo apt-get install -y tzdata

      - name: Get the current date in IST
        id: date
        run: |
          DATE=$(TZ='Asia/Kolkata' date +'%d-%m-%Y') || { echo "Failed to get date"; exit 1; }
          echo "Current date in IST: $DATE"
          echo "DATE=$DATE" >> $GITHUB_ENV
        continue-on-error: false

      - name: Check for commits today
        id: commits
        run: |
          git fetch --unshallow || true  # Ensure full commit history is available
          COMMITS=$(git log --since=midnight --until=now --oneline)
          echo "Commits today: $COMMITS"
          if [ -z "$COMMITS" ]; then
            echo "No commits found today"
            echo "HAS_COMMITS=false" >> $GITHUB_ENV
          else
            echo "Commits found"
            echo "HAS_COMMITS=true" >> $GITHUB_ENV
          fi
        continue-on-error: false

      - name: Create Tag
        if: env.HAS_COMMITS == 'true'
        env:
          TAG_DATE: ${{ env.DATE }}
        run: |
          echo "Checking if tag $TAG_DATE already exists..."
          if git rev-parse $TAG_DATE >/dev/null 2>&1; then
            echo "Tag $TAG_DATE already exists. Skipping tag creation."
            exit 0
          fi
          echo "Creating tag $TAG_DATE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_DATE
          git push origin $TAG_DATE
        continue-on-error: false

      - name: Log success message
        if: success()
        run: echo "Workflow completed successfully"

      - name: Log failure message
        if: failure()
        run: echo "Workflow failed"
