name: Docker Image CI for lr.dj.upayan.dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build react/learning-react --tag ghcr.io/upayanmazumder/devjourney/learning-react:latest --build-arg NODE_ENV=production
          docker push ghcr.io/upayanmazumder/devjourney/learning-react:latest
