name: Docker Image CI for learning-react

on:
  push:
    paths:
      - "react/learning-react/**"
    branches: ["main"]
  pull_request:
    paths:
      - "react/learning-react/**"
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build react/learning-react \
            --tag ghcr.io/upayanmazumder/devjourney/learning-react:latest \
            --build-arg NODE_ENV=production
          docker push ghcr.io/upayanmazumder/devjourney/learning-react:latest

      - name: Notify Keel (GitHub-style webhook)
        run: |
          PAYLOAD=$(jq -n --arg repo "upayanmazumder/devjourney" --arg ref "refs/heads/main" \
            '{repository: {full_name: $repo}, ref: $ref}')

          SIGNATURE=$(echo -n "$PAYLOAD" | openssl sha1 -hmac "${{ secrets.KEEL_WEBHOOK_SECRET }}" | sed 's/^.* //')

          curl -X POST https://keel.upayan.dev/v1/webhooks/github \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature: sha1=$SIGNATURE" \
            -d "$PAYLOAD"
